export const postCategories = [
  "Technology",
  "Health",
  "Finance",
  "Education",
  "Lifestyle",
  "Travel",
  "Food",
  "Fashion",
  "Sports",
  "Entertainment",
  "Science",
  "Politics",
  "Business",
  "Environment",
  "Art",
  "History",
  "Culture",
  "DIY",
  "Parenting",
  "Personal Development",
  "Photography",
  "Gaming",
  "Automotive",
  "Music",
  "Real Estate",
  "Career",
  "Books",
  "Movies",
  "Fitness",
  "Marketing",
  "Startups",
  "Cryptocurrency",
  "Mental Health",
  "Social Media",
  "Spirituality",
  "Gardening",
  "Pets",
  "Crafts",
  "Recipes",
  "Home Improvement",
];
